"""empty message

Revision ID: 302905e07b40
Revises: c13000c832a1
Create Date: 2021-06-17 16:53:31.736163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302905e07b40'
down_revision = 'c13000c832a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###
